/**
 *
 * $Id$
 */
package ca.mcgill.emf.democdsl.validation;


/**
 * A sample validator interface for {@link ca.mcgill.emf.democdsl.Belief}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BeliefValidator {
    boolean validate();

    boolean validateValue(int value);

    boolean validateName(String value);
}
