/**
 *
 * $Id$
 */
package ca.mcgill.emf.democdsl.validation;

import ca.mcgill.emf.democdsl.Constituent;
import ca.mcgill.emf.democdsl.Ideology;
import ca.mcgill.emf.democdsl.Influence;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ca.mcgill.emf.democdsl.DemocDSL}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DemocDSLValidator {
    boolean validate();

    boolean validateConstituents(EList<Constituent> value);
    boolean validateParties(EList<Ideology> value);
    boolean validateName(String value);
    boolean validateInfluences(EList<Influence> value);
}
