/**
 *
 * $Id$
 */
package ca.mcgill.emf.democdsl.validation;

import ca.mcgill.emf.democdsl.Constituent;
import ca.mcgill.emf.democdsl.Ideology;

/**
 * A sample validator interface for {@link ca.mcgill.emf.democdsl.Influence}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InfluenceValidator {
    boolean validate();

    boolean validateWeight(int value);
    boolean validateInfluenced(Constituent value);
    boolean validateInfluencer(Ideology value);
}
